# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: La Cerise sur le Tango
#email: lacerisesurletango@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Cours de tango Argentin à Lyon - Villeurbanne.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lacerisesurletango.fr/" # the base hostname & protocol for your site

# Nombre de posts par page
#paginate: 10

# Build settings
markdown: kramdown

sass:
    style: compressed
